/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x1b5bfc = _0x158b;
function _0x158b(_0x461a01, _0x1d4de6) {
    const _0x3202f7 = _0x3202();
    return _0x158b = function (_0x158bf7, _0x3077f5) {
        _0x158bf7 = _0x158bf7 - 0xe7;
        let _0x359ea8 = _0x3202f7[_0x158bf7];
        return _0x359ea8;
    }, _0x158b(_0x461a01, _0x1d4de6);
}
function _0x3202() {
    const _0x6464d3 = [
        'AXqKA',
        'HcIek',
        'write',
        'Message\x20must\x20be\x20an\x20array',
        'zCYld',
        'CeNPP',
        'application/json',
        'port',
        'error',
        'request',
        'exports',
        '152UvoiWq',
        'service',
        '1312318XmeNEt',
        '42rtzAAM',
        'length',
        '189552khYdeU',
        'serialize',
        'end',
        'deserialize',
        '84276VEoLtV',
        'node',
        '3RqZgxj',
        '650240wnTWqA',
        'jBidZ',
        '555597mGMhId',
        'aOUso',
        'slsQa',
        'data',
        '1487902tgGZlM',
        'bDyXG',
        '29064710ymRNLM',
        'Error\x20on\x20request'
    ];
    _0x3202 = function () {
        return _0x6464d3;
    };
    return _0x3202();
}
(function (_0x435882, _0x238bf0) {
    const _0x2a58e5 = _0x158b, _0x5a2876 = _0x435882();
    while (!![]) {
        try {
            const _0x11029e = -parseInt(_0x2a58e5(0xf9)) / 0x1 + parseInt(_0x2a58e5(0xf0)) / 0x2 + parseInt(_0x2a58e5(0xf2)) / 0x3 * (-parseInt(_0x2a58e5(0xec)) / 0x4) + parseInt(_0x2a58e5(0xf3)) / 0x5 * (parseInt(_0x2a58e5(0xea)) / 0x6) + -parseInt(_0x2a58e5(0xe9)) / 0x7 + -parseInt(_0x2a58e5(0xe7)) / 0x8 * (parseInt(_0x2a58e5(0xf5)) / 0x9) + parseInt(_0x2a58e5(0xfb)) / 0xa;
            if (_0x11029e === _0x238bf0)
                break;
            else
                _0x5a2876['push'](_0x5a2876['shift']());
        } catch (_0x29b667) {
            _0x5a2876['push'](_0x5a2876['shift']());
        }
    }
}(_0x3202, 0xeb2b6));
const http = require('http'), serialization = require('../util/serialization'), comm = {};
comm['send'] = function (_0x334090, _0x469256, _0x8f0bcc) {
    const _0xce95fc = _0x158b, _0x259c89 = {
            'slsQa': function (_0x1f354d, ..._0x4a9a45) {
                return _0x1f354d(..._0x4a9a45);
            },
            'CeNPP': function (_0x59e922, _0x4639dd) {
                return _0x59e922(_0x4639dd);
            },
            'CqpAj': 'Error\x20on\x20response',
            'bDyXG': _0xce95fc(0xee),
            'AXqKA': _0xce95fc(0x105),
            'aOUso': _0xce95fc(0x100),
            'SysBN': function (_0x4b33b5, _0x6d1407) {
                return _0x4b33b5 + _0x6d1407;
            },
            'UNgnr': 'PUT',
            'zCYld': _0xce95fc(0x103)
        };
    if (!_0x334090 instanceof Array)
        throw new Error(_0x259c89[_0xce95fc(0xf6)]);
    let _0x1b1f69 = _0x469256[_0xce95fc(0xf1)], _0x35782e = _0x469256[_0xce95fc(0xe8)], _0x10672b = _0x469256['method'], _0xe7be08 = serialization[_0xce95fc(0xed)](_0x334090);
    const _0x2a6dc0 = {
            'hostname': _0x1b1f69['ip'],
            'port': _0x1b1f69[_0xce95fc(0x104)],
            'path': _0x259c89['SysBN']('/' + _0x35782e + '/', _0x10672b),
            'method': _0x259c89['UNgnr'],
            'headers': {
                'Content-Type': _0x259c89[_0xce95fc(0x101)],
                'Content-Length': _0xe7be08[_0xce95fc(0xeb)]
            }
        }, _0x3cb9e0 = http[_0xce95fc(0x106)](_0x2a6dc0, _0x38a754 => {
            const _0x549f38 = _0xce95fc, _0x38c71c = {
                    'jBidZ': function (_0x5e8904, _0x5493f1) {
                        const _0x5958dc = _0x158b;
                        return _0x259c89[_0x5958dc(0x102)](_0x5e8904, _0x5493f1);
                    },
                    'HcIek': _0x259c89['CqpAj']
                };
            let _0x21ff68 = '';
            _0x38a754['on'](_0x549f38(0xf8), function (_0x29ead1) {
                _0x21ff68 += _0x29ead1;
            }), _0x38a754['on'](_0x259c89[_0x549f38(0xfa)], function () {
                const _0xc544dc = _0x549f38;
                _0x8f0bcc && _0x259c89[_0xc544dc(0xf7)](_0x8f0bcc, ...serialization[_0xc544dc(0xef)](_0x21ff68));
            }), _0x38a754['on'](_0x259c89[_0x549f38(0xfd)], function (_0x417e13) {
                const _0x4f5100 = _0x549f38;
                _0x8f0bcc && _0x38c71c[_0x4f5100(0xf4)](_0x8f0bcc, new Error(_0x38c71c[_0x4f5100(0xfe)]));
            });
        });
    _0x3cb9e0['on'](_0x259c89[_0xce95fc(0xfd)], function (_0x14f79a) {
        const _0x21358e = _0xce95fc;
        _0x8f0bcc && _0x259c89[_0x21358e(0x102)](_0x8f0bcc, new Error(_0x21358e(0xfc)));
    }), _0x3cb9e0[_0xce95fc(0xff)](_0xe7be08), _0x3cb9e0['end']();
}, module[_0x1b5bfc(0x107)] = comm;/* eslint-enable */
