/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
function _0x593d(_0x444266, _0x1827c0) {
    const _0xea5422 = _0xea54();
    return _0x593d = function (_0x593d76, _0x1c2b54) {
        _0x593d76 = _0x593d76 - 0x1cd;
        let _0x39ac0d = _0xea5422[_0x593d76];
        return _0x39ac0d;
    }, _0x593d(_0x444266, _0x1827c0);
}
const _0x2d9405 = _0x593d;
function _0xea54() {
    const _0x451589 = [
        '55RLFsEl',
        '380514TvmPlO',
        'method',
        'length',
        'error',
        'PUT',
        'application/json',
        'MbLXh',
        'port',
        'deserialize',
        '34917qvzsMq',
        '27SYXIPY',
        '62094YEjCvG',
        'uTtpp',
        'write',
        'kWxiA',
        'send',
        'data',
        'node',
        'vtXbu',
        'gdRpC',
        '22dNOfyG',
        '794892AVXvAS',
        'exports',
        '103120PGbtlO',
        'Message\x20must\x20be\x20an\x20array',
        'Error\x20sending\x20message',
        '1411672ldsHaZ',
        'zmHke',
        'end',
        'HTIVn',
        '2405655uoVqhv',
        'evSpL',
        'service'
    ];
    _0xea54 = function () {
        return _0x451589;
    };
    return _0xea54();
}
(function (_0x42735c, _0x5927a4) {
    const _0x1a07ab = _0x593d, _0x502d24 = _0x42735c();
    while (!![]) {
        try {
            const _0x11e635 = parseInt(_0x1a07ab(0x1d9)) / 0x1 + parseInt(_0x1a07ab(0x1ed)) / 0x2 * (parseInt(_0x1a07ab(0x1e2)) / 0x3) + -parseInt(_0x1a07ab(0x1ee)) / 0x4 + -parseInt(_0x1a07ab(0x1d8)) / 0x5 * (-parseInt(_0x1a07ab(0x1e4)) / 0x6) + -parseInt(_0x1a07ab(0x1d5)) / 0x7 + parseInt(_0x1a07ab(0x1d1)) / 0x8 + parseInt(_0x1a07ab(0x1e3)) / 0x9 * (-parseInt(_0x1a07ab(0x1ce)) / 0xa);
            if (_0x11e635 === _0x5927a4)
                break;
            else
                _0x502d24['push'](_0x502d24['shift']());
        } catch (_0x3d9751) {
            _0x502d24['push'](_0x502d24['shift']());
        }
    }
}(_0xea54, 0x370ed));
const http = require('http'), serialization = require('../util/serialization'), comm = {};
comm[_0x2d9405(0x1e8)] = function (_0x35eea4, _0x250614, _0x10d14e) {
    const _0x6a55d4 = _0x2d9405, _0x1ca4cf = {
            'gdRpC': function (_0x2ef590, ..._0x30671f) {
                return _0x2ef590(..._0x30671f);
            },
            'uTtpp': _0x6a55d4(0x1e9),
            'kWxiA': _0x6a55d4(0x1dc),
            'HTIVn': _0x6a55d4(0x1d0),
            'evSpL': function (_0x54c6ae, _0x213c93) {
                return _0x54c6ae instanceof _0x213c93;
            },
            'vtXbu': _0x6a55d4(0x1cf),
            'zmHke': function (_0x1050ec, _0x2172c8) {
                return _0x1050ec + _0x2172c8;
            },
            'MbLXh': _0x6a55d4(0x1dd)
        };
    if (_0x1ca4cf[_0x6a55d4(0x1d6)](!_0x35eea4, Array))
        throw new Error(_0x1ca4cf[_0x6a55d4(0x1eb)]);
    let _0x58c148 = _0x250614[_0x6a55d4(0x1ea)], _0x534631 = _0x250614[_0x6a55d4(0x1d7)], _0x260180 = _0x250614[_0x6a55d4(0x1da)], _0xd971c3 = serialization['serialize'](_0x35eea4);
    const _0x1fb9de = {
            'hostname': _0x58c148['ip'],
            'port': _0x58c148[_0x6a55d4(0x1e0)],
            'path': _0x1ca4cf[_0x6a55d4(0x1d2)](_0x1ca4cf[_0x6a55d4(0x1d2)]('/' + _0x534631, '/'), _0x260180),
            'method': _0x1ca4cf[_0x6a55d4(0x1df)],
            'headers': {
                'Content-Type': _0x6a55d4(0x1de),
                'Content-Length': _0xd971c3[_0x6a55d4(0x1db)]
            }
        }, _0x23adeb = http['request'](_0x1fb9de, _0x360403 => {
            const _0x318db1 = _0x6a55d4, _0x21be3b = {
                    'YRqTD': function (_0x518768, _0x1abf4f) {
                        return _0x518768(_0x1abf4f);
                    }
                };
            let _0x2e0a5d = '';
            _0x360403['on'](_0x1ca4cf[_0x318db1(0x1e5)], function (_0x33020e) {
                _0x2e0a5d += _0x33020e;
            }), _0x360403['on'](_0x318db1(0x1d3), function () {
                const _0x19d80e = _0x318db1;
                _0x10d14e && _0x1ca4cf[_0x19d80e(0x1ec)](_0x10d14e, ...serialization[_0x19d80e(0x1e1)](_0x2e0a5d));
            }), _0x360403['on'](_0x1ca4cf['kWxiA'], function (_0xd7c316) {
                _0x10d14e && _0x21be3b['YRqTD'](_0x10d14e, new Error('Error\x20sending\x20message'));
            });
        });
    _0x23adeb['on'](_0x1ca4cf[_0x6a55d4(0x1e7)], function (_0x495224) {
        const _0x46b087 = _0x6a55d4;
        _0x10d14e && _0x10d14e(new Error(_0x1ca4cf[_0x46b087(0x1d4)]));
    }), _0x23adeb[_0x6a55d4(0x1e6)](_0xd971c3), _0x23adeb[_0x6a55d4(0x1d3)]();
}, module[_0x2d9405(0x1cd)] = comm;/* eslint-enable */
