/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
function _0x40ee() {
    const _0x21307d = [
        'groups',
        '10aKwIFr',
        'status',
        'put',
        '1007720bAUOGI',
        'exports',
        '2237949MnWNwG',
        'toLocal',
        '900101dUAgvU',
        '1016817YDoSJk',
        '390WDkKwp',
        'oaiDm',
        '2121462EigjEn',
        '9818688Lnufqh',
        '30215eSRYkH',
        '2NToWOo',
        'gossip',
        '8oBUQkJ',
        'get',
        'toWAi',
        'Service\x20not\x20found\x20in\x20routes'
    ];
    _0x40ee = function () {
        return _0x21307d;
    };
    return _0x40ee();
}
const _0x1fa617 = _0x208d;
(function (_0xa1e94d, _0x27d8dc) {
    const _0x260392 = _0x208d, _0x48c0c6 = _0xa1e94d();
    while (!![]) {
        try {
            const _0x39fe11 = parseInt(_0x260392(0x111)) / 0x1 + -parseInt(_0x260392(0x118)) / 0x2 * (-parseInt(_0x260392(0x112)) / 0x3) + -parseInt(_0x260392(0x10d)) / 0x4 + parseInt(_0x260392(0x117)) / 0x5 * (-parseInt(_0x260392(0x113)) / 0x6) + -parseInt(_0x260392(0x10f)) / 0x7 * (parseInt(_0x260392(0x11a)) / 0x8) + -parseInt(_0x260392(0x115)) / 0x9 * (parseInt(_0x260392(0x10a)) / 0xa) + parseInt(_0x260392(0x116)) / 0xb;
            if (_0x39fe11 === _0x27d8dc)
                break;
            else
                _0x48c0c6['push'](_0x48c0c6['shift']());
        } catch (_0xd403c7) {
            _0x48c0c6['push'](_0x48c0c6['shift']());
        }
    }
}(_0x40ee, 0xe36aa));
function _0x208d(_0x5b7ea9, _0xa8bf53) {
    const _0x40ee21 = _0x40ee();
    return _0x208d = function (_0x208d7, _0x3c1137) {
        _0x208d7 = _0x208d7 - 0x106;
        let _0x2ece44 = _0x40ee21[_0x208d7];
        return _0x2ece44;
    }, _0x208d(_0x5b7ea9, _0xa8bf53);
}
const routesStore = new Map(), routes = {};
routes[_0x1fa617(0x106)] = function (_0xa8ad72, _0x28b20a) {
    const _0x30a03d = _0x1fa617, _0x33d824 = {
            'toWAi': function (_0x194dd2, _0x3a0168, _0x478077) {
                return _0x194dd2(_0x3a0168, _0x478077);
            },
            'oaiDm': function (_0x1f97fc, _0x3f7e3d) {
                return _0x1f97fc(_0x3f7e3d);
            },
            'drhwa': _0x30a03d(0x108)
        };
    if (!_0x28b20a)
        return;
    if (_0xa8ad72 in routesStore) {
        let _0x51a01 = routesStore[_0xa8ad72];
        _0x33d824[_0x30a03d(0x107)](_0x28b20a, null, _0x51a01);
    } else {
        const _0x241480 = global[_0x30a03d(0x110)][_0x30a03d(0x106)](_0xa8ad72);
        _0x241480 ? _0x33d824['toWAi'](_0x28b20a, null, { 'call': _0x241480 }) : _0x33d824[_0x30a03d(0x114)](_0x28b20a, new Error(_0x33d824['drhwa']));
    }
}, routes[_0x1fa617(0x10c)] = function (_0x15396e, _0x5ef3ef, _0x4bc610) {
    const _0x485b50 = {
        'tVACT': function (_0x113247, _0x34b65a, _0x5bf974) {
            return _0x113247(_0x34b65a, _0x5bf974);
        }
    };
    routesStore[_0x5ef3ef] = _0x15396e;
    _0x4bc610 && _0x485b50['tVACT'](_0x4bc610, null, _0x5ef3ef);
    ;
};
const comm = require('./comm'), status = require('./status'), groups = require('./groups'), gossip = require('./gossip');
routesStore['routes'] = routes, routesStore['comm'] = comm, routesStore[_0x1fa617(0x10b)] = status, routesStore[_0x1fa617(0x109)] = groups, routesStore[_0x1fa617(0x119)] = gossip, module[_0x1fa617(0x10e)] = routes;/* eslint-enable */
