/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x20675f = _0x2567;
function _0x3114() {
    const _0x3172be = [
        '30792yMfuMa',
        'routes',
        'XVzci',
        'status',
        '96CDBrWj',
        'gossip',
        '2050686WaLalm',
        'xYLGY',
        '6AxqsEA',
        'put',
        '1917952pYXKBH',
        'toLocal',
        '10660390lnxwvQ',
        'groups',
        'LQklO',
        'wesej',
        '1179563cxzdDl',
        '11785YKbFKX',
        '1038YnAdvZ',
        'get',
        'ulsRD',
        'Service\x20not\x20found\x20in\x20routes',
        '18mdZKms',
        'comm'
    ];
    _0x3114 = function () {
        return _0x3172be;
    };
    return _0x3114();
}
function _0x2567(_0x26ace9, _0x563e9a) {
    const _0x3114cf = _0x3114();
    return _0x2567 = function (_0x256772, _0x158f88) {
        _0x256772 = _0x256772 - 0xb5;
        let _0x4b0016 = _0x3114cf[_0x256772];
        return _0x4b0016;
    }, _0x2567(_0x26ace9, _0x563e9a);
}
(function (_0xf5aba, _0x4238cc) {
    const _0x276ba3 = _0x2567, _0x574183 = _0xf5aba();
    while (!![]) {
        try {
            const _0x1c863e = parseInt(_0x276ba3(0xc4)) / 0x1 * (-parseInt(_0x276ba3(0xc6)) / 0x2) + -parseInt(_0x276ba3(0xc0)) / 0x3 * (parseInt(_0x276ba3(0xca)) / 0x4) + -parseInt(_0x276ba3(0xbf)) / 0x5 * (-parseInt(_0x276ba3(0xb6)) / 0x6) + -parseInt(_0x276ba3(0xbe)) / 0x7 + -parseInt(_0x276ba3(0xb8)) / 0x8 + -parseInt(_0x276ba3(0xcc)) / 0x9 + parseInt(_0x276ba3(0xba)) / 0xa;
            if (_0x1c863e === _0x4238cc)
                break;
            else
                _0x574183['push'](_0x574183['shift']());
        } catch (_0x90b91f) {
            _0x574183['push'](_0x574183['shift']());
        }
    }
}(_0x3114, 0x23da9));
const routesStore = new Map(), routes = {};
routes[_0x20675f(0xc1)] = function (_0x2ba3c7, _0x51513d) {
    const _0xa4504d = _0x20675f, _0x416894 = {
            'XVzci': function (_0xb08d6e, _0x3bee4e) {
                return _0xb08d6e in _0x3bee4e;
            },
            'wesej': function (_0x33bd67, _0x1fd866, _0x2f7d7e) {
                return _0x33bd67(_0x1fd866, _0x2f7d7e);
            },
            'LQklO': function (_0x1ca57f, _0xeeb080, _0x143e5d) {
                return _0x1ca57f(_0xeeb080, _0x143e5d);
            },
            'xYLGY': function (_0x4a8ec6, _0x3771d2) {
                return _0x4a8ec6(_0x3771d2);
            },
            'ulsRD': _0xa4504d(0xc3)
        };
    if (!_0x51513d)
        return;
    if (_0x416894[_0xa4504d(0xc8)](_0x2ba3c7, routesStore)) {
        let _0x3207f7 = routesStore[_0x2ba3c7];
        _0x416894[_0xa4504d(0xbd)](_0x51513d, null, _0x3207f7);
    } else {
        const _0x41d9e1 = global[_0xa4504d(0xb9)]['get'](_0x2ba3c7);
        _0x41d9e1 ? _0x416894[_0xa4504d(0xbc)](_0x51513d, null, { 'call': _0x41d9e1 }) : _0x416894[_0xa4504d(0xb5)](_0x51513d, new Error(_0x416894[_0xa4504d(0xc2)]));
    }
}, routes[_0x20675f(0xb7)] = function (_0x3d242f, _0x2c53dc, _0x256ee4) {
    routesStore[_0x2c53dc] = _0x3d242f;
    _0x256ee4 && _0x256ee4(null, _0x2c53dc);
    ;
};
const comm = require('./comm'), status = require('./status'), groups = require('./groups'), gossip = require('./gossip');
routesStore[_0x20675f(0xc7)] = routes, routesStore[_0x20675f(0xc5)] = comm, routesStore[_0x20675f(0xc9)] = status, routesStore[_0x20675f(0xbb)] = groups, routesStore[_0x20675f(0xcb)] = gossip, module['exports'] = routes;/* eslint-enable */
