/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x30d1e2 = _0x235a;
(function (_0x570700, _0xb1441c) {
    const _0x328e8c = _0x235a, _0x425f0c = _0x570700();
    while (!![]) {
        try {
            const _0x281717 = parseInt(_0x328e8c(0x224)) / 0x1 + parseInt(_0x328e8c(0x1d2)) / 0x2 * (-parseInt(_0x328e8c(0x1d9)) / 0x3) + -parseInt(_0x328e8c(0x209)) / 0x4 * (-parseInt(_0x328e8c(0x22a)) / 0x5) + -parseInt(_0x328e8c(0x1f7)) / 0x6 * (-parseInt(_0x328e8c(0x1ba)) / 0x7) + parseInt(_0x328e8c(0x1ee)) / 0x8 * (-parseInt(_0x328e8c(0x1bc)) / 0x9) + -parseInt(_0x328e8c(0x219)) / 0xa + -parseInt(_0x328e8c(0x1b7)) / 0xb * (parseInt(_0x328e8c(0x1f8)) / 0xc);
            if (_0x281717 === _0xb1441c)
                break;
            else
                _0x425f0c['push'](_0x425f0c['shift']());
        } catch (_0x331fe8) {
            _0x425f0c['push'](_0x425f0c['shift']());
        }
    }
}(_0x561f, 0x21eab));
function _0x561f() {
    const _0x403a13 = [
        'number',
        'axHyK',
        'message',
        'ChCnf',
        'undefined',
        'vkSrv',
        'reference',
        '$reference',
        'kWfCY',
        'stringify',
        '{\x20[native\x20code]\x20}',
        'ZkGPb',
        'WiReA',
        'aDYdg',
        'ZzIBI',
        '44698LFCdqi',
        'fiXiR',
        'uuCKA',
        'lzSyh',
        'TRVvj',
        'yFmCy',
        'zfhBf',
        '3AOqpgT',
        'type',
        'push',
        'url',
        'split',
        'exports',
        'cypgC',
        'OamJj',
        'SzmFS',
        'mfZPW',
        'function',
        'WEVCo',
        'GwmLf',
        'toJSON',
        'isNWk',
        'forEach',
        'OnpHi',
        'CbvOK',
        'keys',
        'null',
        'DWMyn',
        '344712ZlvGhK',
        'has',
        'rFYmN',
        'indexOf',
        'IUchA',
        'VnlSE',
        'forward',
        'entries',
        '[native\x20code]',
        '204fadHAd',
        '24hvGJgc',
        'NLnmM',
        'rMiTf',
        'boolean',
        'XFsRU',
        'dgram',
        'native',
        'NsyDJ',
        'object',
        'HqUIt',
        'lUeLQ',
        'AgqVb',
        'fWUXz',
        'aQDsY',
        'stream',
        'xXnWn',
        'lFbdm',
        '160xRTeda',
        'dhjol',
        'sCTPg',
        'wKBUi',
        'parse',
        'reverse',
        'VfaPz',
        'value',
        'child_process',
        'KMNFN',
        'includes',
        'iuRgm',
        'HTchP',
        'TzJKo',
        'ZoQnO',
        'isArray',
        '676290bHwxGJ',
        'globalThis',
        'tOlXV',
        '2|1|0|3|4',
        'toString',
        'util',
        'Koncl',
        'Invalid\x20argument\x20type:\x20',
        'SiOHQ',
        'get',
        'zhUcH',
        '256770VoEsYE',
        'fWXUG',
        'getOwnPropertyNames',
        'VHMWQ',
        'return\x20',
        'cluster',
        '9030ZBvWjW',
        'LZVSG',
        'qdxAf',
        'cause',
        'zlib',
        'string',
        'WITvD',
        'date',
        'KQyOP',
        'error',
        'KxZSk',
        'MJnNl',
        '1674783TDbTfH',
        'http',
        'FeGDN',
        '50953ODFcBs',
        'KXejS',
        '9VHRjZY',
        'querystring',
        'msQyQ',
        'set',
        'buffer',
        'EWYCF',
        'yuHQL'
    ];
    _0x561f = function () {
        return _0x403a13;
    };
    return _0x561f();
}
var nativeFunctions = {
    'forward': new Map(),
    'reverse': new Map()
};
function isNativeFunction(_0x36b513) {
    const _0x215ce8 = _0x235a, _0x1511e2 = {
            'zhUcH': function (_0x4ea1d6, _0x1e4820) {
                return _0x4ea1d6 === _0x1e4820;
            },
            'FeGDN': _0x215ce8(0x1f6),
            'KXejS': function (_0x23a475, _0x2d27fb) {
                return _0x23a475 > _0x2d27fb;
            },
            'fiXiR': _0x215ce8(0x1cd)
        };
    return _0x1511e2[_0x215ce8(0x223)](typeof _0x36b513, _0x215ce8(0x1e3)) && (_0x36b513[_0x215ce8(0x21d)]()[_0x215ce8(0x213)](_0x1511e2[_0x215ce8(0x1b9)]) || _0x1511e2[_0x215ce8(0x1bb)](_0x36b513[_0x215ce8(0x21d)]()[_0x215ce8(0x1f1)](_0x1511e2[_0x215ce8(0x1d3)]), -0x1));
}
function createNativeMap() {
    const _0x12a405 = _0x235a, _0x287692 = {
            'yuHQL': function (_0x37b8c2, _0x39329b) {
                return _0x37b8c2(_0x39329b);
            },
            'KxZSk': function (_0x5bbf9e, _0x1ef679) {
                return _0x5bbf9e + _0x1ef679;
            },
            'fWXUG': function (_0x12c45d, _0x353c0e) {
                return _0x12c45d === _0x353c0e;
            },
            'ZoQnO': function (_0x39d655, _0x599295) {
                return _0x39d655 === _0x599295;
            },
            'xXnWn': function (_0x333204, _0x40e6d3, _0x4824c4) {
                return _0x333204(_0x40e6d3, _0x4824c4);
            },
            'uGjBh': _0x12a405(0x21a),
            'VHMWQ': function (_0x4c4f2c, _0x2ba672, _0x20896d) {
                return _0x4c4f2c(_0x2ba672, _0x20896d);
            },
            'LqVBw': _0x12a405(0x1b8),
            'WITvD': 'https',
            'lUeLQ': _0x12a405(0x1dc),
            'zfhBf': 'path',
            'lzSyh': function (_0x4a09e8, _0x8231aa, _0x15b1fe) {
                return _0x4a09e8(_0x8231aa, _0x15b1fe);
            },
            'ChCnf': 'events',
            'WEVCo': function (_0x11545d, _0x3d9a6a, _0x163b6f) {
                return _0x11545d(_0x3d9a6a, _0x163b6f);
            },
            'Koncl': _0x12a405(0x206),
            'vkSrv': function (_0x2b791f, _0x853816, _0x32d3c7) {
                return _0x2b791f(_0x853816, _0x32d3c7);
            },
            'HTchP': _0x12a405(0x21e),
            'SzmFS': _0x12a405(0x1bd),
            'aDYdg': _0x12a405(0x1c0),
            'LEwxc': function (_0x1d352e, _0x149ac9, _0x51374a) {
                return _0x1d352e(_0x149ac9, _0x51374a);
            },
            'FJivI': _0x12a405(0x211),
            'ZiGWR': _0x12a405(0x229),
            'VfaPz': 'dns',
            'aQDsY': 'http2'
        };
    var _0xf0074 = [];
    function _0x1d75a6(_0xc72db6, _0x4a1caa) {
        const _0x34ad33 = _0x12a405, _0x4d4999 = {
                'NsyDJ': function (_0x3988a2, _0x3afc09) {
                    const _0x10dca4 = _0x235a;
                    return _0x287692[_0x10dca4(0x1c2)](_0x3988a2, _0x3afc09);
                },
                'TzJKo': function (_0x5179d2, _0x476f6a) {
                    return _0x287692['KxZSk'](_0x5179d2, _0x476f6a);
                },
                'XoHAV': function (_0x169740, _0x235b81) {
                    const _0x4fa040 = _0x235a;
                    return _0x287692[_0x4fa040(0x1b5)](_0x169740, _0x235b81);
                },
                'EWYCF': function (_0x3367bb, _0x345134) {
                    const _0x3f0902 = _0x235a;
                    return _0x287692[_0x3f0902(0x225)](_0x3367bb, _0x345134);
                },
                'PoNLv': function (_0x4b93be, _0x40599a, _0x334d2b) {
                    return _0x4b93be(_0x40599a, _0x334d2b);
                }
            };
        if (_0x287692[_0x34ad33(0x217)](_0x4a1caa, null) || _0x4a1caa === undefined)
            return;
        if (_0xf0074[_0x34ad33(0x1f1)](_0x4a1caa) !== -0x1)
            return;
        _0xf0074[_0x34ad33(0x1db)](_0x4a1caa), Object[_0x34ad33(0x226)](_0x4a1caa)['forEach'](_0x13205a => {
            const _0x2236cb = _0x34ad33;
            if (_0x4d4999[_0x2236cb(0x1ff)](isNativeFunction, _0x4a1caa[_0x13205a])) {
                nativeFunctions[_0x2236cb(0x1f4)][_0x2236cb(0x1bf)](_0x4a1caa[_0x13205a], _0x4d4999[_0x2236cb(0x216)](_0xc72db6, '.') + _0x13205a), nativeFunctions[_0x2236cb(0x20e)][_0x2236cb(0x1bf)](_0x4d4999['XoHAV'](_0x4d4999[_0x2236cb(0x216)](_0xc72db6, '.'), _0x13205a), _0x4a1caa[_0x13205a]);
                return;
            }
            _0x4d4999[_0x2236cb(0x1c1)](typeof _0x4a1caa[_0x13205a], _0x2236cb(0x200)) && _0x4d4999[_0x2236cb(0x1c1)](_0xf0074[_0x2236cb(0x1f1)](_0x4a1caa[_0x13205a]), -0x1) && _0x4d4999['PoNLv'](_0x1d75a6, _0x4d4999['XoHAV'](_0xc72db6 + '.', _0x13205a), _0x4a1caa[_0x13205a]);
        });
    }
    const _0x4702e1 = require('fs'), _0x1b5ebf = require('http'), _0x5e84d1 = require('https'), _0x493d83 = require('url'), _0x1af14f = require('path'), _0x2c05c5 = require('os'), _0x561c5f = require('events'), _0x1252eb = require('stream'), _0x44503d = require('util'), _0xb6eaef = require('querystring'), _0x5a71f3 = require('zlib'), _0xf12187 = require('buffer'), _0x5637c5 = require('child_process'), _0x57c62b = require('cluster'), _0x52d3aa = require('dgram'), _0x43f7ef = require('dns'), _0x21fcee = require('http2'), _0x28d114 = require('v8');
    _0x287692[_0x12a405(0x207)](_0x1d75a6, _0x287692['uGjBh'], globalThis), _0x287692[_0x12a405(0x227)](_0x1d75a6, 'fs', _0x4702e1), _0x287692['xXnWn'](_0x1d75a6, _0x287692['LqVBw'], _0x1b5ebf), _0x1d75a6(_0x287692[_0x12a405(0x230)], _0x5e84d1), _0x287692['VHMWQ'](_0x1d75a6, _0x287692[_0x12a405(0x202)], _0x493d83), _0x287692[_0x12a405(0x207)](_0x1d75a6, _0x287692[_0x12a405(0x1d8)], _0x1af14f), _0x287692[_0x12a405(0x1d5)](_0x1d75a6, 'os', _0x2c05c5), _0x1d75a6(_0x287692[_0x12a405(0x1c6)], _0x561c5f), _0x287692[_0x12a405(0x1e4)](_0x1d75a6, _0x287692[_0x12a405(0x21f)], _0x1252eb), _0x287692['vkSrv'](_0x1d75a6, _0x287692[_0x12a405(0x215)], _0x44503d), _0x287692[_0x12a405(0x1c8)](_0x1d75a6, _0x287692[_0x12a405(0x1e1)], _0xb6eaef), _0x287692['xXnWn'](_0x1d75a6, _0x12a405(0x22e), _0x5a71f3), _0x287692[_0x12a405(0x1d5)](_0x1d75a6, _0x287692[_0x12a405(0x1d0)], _0xf12187), _0x287692['LEwxc'](_0x1d75a6, _0x287692['FJivI'], _0x5637c5), _0x287692[_0x12a405(0x227)](_0x1d75a6, _0x287692['ZiGWR'], _0x57c62b), _0x287692['xXnWn'](_0x1d75a6, _0x12a405(0x1fd), _0x52d3aa), _0x287692[_0x12a405(0x227)](_0x1d75a6, _0x287692[_0x12a405(0x20f)], _0x43f7ef), _0x1d75a6(_0x287692[_0x12a405(0x205)], _0x21fcee), _0x287692[_0x12a405(0x1c8)](_0x1d75a6, 'v8', _0x28d114);
}
createNativeMap();
function decycleObject(_0x55c9c6) {
    const _0x2bb223 = _0x235a, _0xb997ea = {
            'iuRgm': function (_0x5e182d, _0x3b8940, _0x1fc927) {
                return _0x5e182d(_0x3b8940, _0x1fc927);
            },
            'VnlSE': function (_0x51692d, _0x58695c) {
                return _0x51692d === _0x58695c;
            },
            'AVSKG': _0x2bb223(0x200),
            'XFsRU': function (_0x102952, _0x4e803e) {
                return _0x102952 instanceof _0x4e803e;
            },
            'axHyK': function (_0xaf97d9, _0x3c5fc9) {
                return _0xaf97d9 instanceof _0x3c5fc9;
            },
            'LZVSG': function (_0x32af61, _0x44775b) {
                return _0x32af61 !== _0x44775b;
            }
        };
    if (_0xb997ea[_0x2bb223(0x1f3)](_0x55c9c6, null) || _0x55c9c6 === undefined)
        return _0x55c9c6;
    var _0x4abb9f = new WeakMap();
    function _0x55533d(_0x3d8215, _0x8d20b4) {
        const _0x43128e = _0x2bb223, _0x238d54 = {
                'SQsKm': function (_0x50ff59, _0x143abc, _0x13745b) {
                    const _0x1eeb10 = _0x235a;
                    return _0xb997ea[_0x1eeb10(0x214)](_0x50ff59, _0x143abc, _0x13745b);
                }
            };
        var _0x1c5518, _0x5a0bf2;
        if (!(_0xb997ea[_0x43128e(0x1f3)](typeof _0x3d8215, _0xb997ea['AVSKG']) && !_0xb997ea[_0x43128e(0x1fc)](_0x3d8215, Error) && !_0xb997ea[_0x43128e(0x1c4)](_0x3d8215, Date) && !_0xb997ea[_0x43128e(0x1fc)](_0x3d8215, Boolean) && _0xb997ea[_0x43128e(0x22b)](_0x3d8215, null)))
            return _0x3d8215;
        _0x1c5518 = _0x4abb9f[_0x43128e(0x222)](_0x3d8215);
        if (_0xb997ea[_0x43128e(0x22b)](_0x1c5518, undefined))
            return { '$reference': _0x1c5518 };
        return _0x4abb9f['set'](_0x3d8215, _0x8d20b4), Array[_0x43128e(0x218)](_0x3d8215) ? (_0x5a0bf2 = [], _0x3d8215[_0x43128e(0x1e8)](function (_0x21873b, _0x3368db) {
            let _0x37c1a0 = [
                ..._0x8d20b4,
                _0x3368db
            ];
            _0x5a0bf2[_0x3368db] = _0x238d54['SQsKm'](_0x55533d, _0x21873b, _0x37c1a0);
        })) : (_0x5a0bf2 = {}, Object['keys'](_0x3d8215)[_0x43128e(0x1e8)](_0x96a868 => {
            const _0x4c09fa = _0x43128e;
            let _0x432244 = [
                ..._0x8d20b4,
                JSON[_0x4c09fa(0x1cc)](_0x96a868)
            ];
            _0x5a0bf2[_0x96a868] = _0x55533d(_0x3d8215[_0x96a868], _0x432244);
        })), _0x5a0bf2;
    }
    return _0x55533d(_0x55c9c6, []);
}
;
function serializeBaseStructure(_0x5a70f8) {
    return {
        'type': typeof _0x5a70f8,
        'value': _0x5a70f8['toString']()
    };
}
function serializeUndefined(_0x677251) {
    const _0x5e0863 = _0x235a;
    return {
        'type': _0x5e0863(0x1c7),
        'value': ''
    };
}
function getObjectSubType(_0x23c561) {
    const _0x37f439 = _0x235a, _0x47b02b = {
            'AgqVb': function (_0x35d803, _0x2d54ac) {
                return _0x35d803 instanceof _0x2d54ac;
            },
            'KQyOP': 'error',
            'MJnNl': _0x37f439(0x231),
            'IUchA': function (_0x1555e6, _0x1c9c3a) {
                return _0x1555e6 instanceof _0x1c9c3a;
            },
            'EjXKE': 'array',
            'HbfKg': function (_0x420b10, _0xb0aaf8) {
                return _0x420b10 === _0xb0aaf8;
            }
        }, _0x370903 = _0x37f439(0x21c)[_0x37f439(0x1dd)]('|');
    let _0x4791ee = 0x0;
    while (!![]) {
        switch (_0x370903[_0x4791ee++]) {
        case '0':
            if (_0x47b02b[_0x37f439(0x203)](_0x23c561, Error))
                return _0x47b02b[_0x37f439(0x232)];
            continue;
        case '1':
            if (_0x47b02b['AgqVb'](_0x23c561, Date))
                return _0x47b02b[_0x37f439(0x1b6)];
            continue;
        case '2':
            if (_0x47b02b[_0x37f439(0x1f2)](_0x23c561, Array))
                return _0x47b02b['EjXKE'];
            continue;
        case '3':
            if (_0x47b02b['HbfKg'](_0x23c561, null))
                return _0x37f439(0x1ec);
            continue;
        case '4':
            return _0x37f439(0x200);
        }
        break;
    }
}
function serializeObject(_0x197351) {
    const _0x3f462a = _0x235a, _0x5f3c87 = {
            'rMiTf': function (_0x30ced3, _0x414f15) {
                return _0x30ced3 == _0x414f15;
            },
            'fWUXz': function (_0x29a6b5, _0x48a0a3) {
                return _0x29a6b5(_0x48a0a3);
            },
            'JXYIR': _0x3f462a(0x1ec),
            'ZkGPb': function (_0x4ed992, _0x482f35) {
                return _0x4ed992 === _0x482f35;
            },
            'cypgC': _0x3f462a(0x231),
            'yFmCy': _0x3f462a(0x1b4),
            'NLnmM': function (_0x31a745, _0x5cd11b) {
                return _0x31a745(_0x5cd11b);
            },
            'HqUIt': 'reference',
            'kWfCY': _0x3f462a(0x1ca)
        };
    let _0x2ccaef = _0x5f3c87[_0x3f462a(0x204)](getObjectSubType, _0x197351);
    if (_0x2ccaef === _0x5f3c87['JXYIR'])
        return {
            'type': _0x2ccaef,
            'value': ''
        };
    if (_0x5f3c87['ZkGPb'](_0x2ccaef, _0x5f3c87[_0x3f462a(0x1df)]))
        return {
            'type': _0x2ccaef,
            'value': _0x197351[_0x3f462a(0x1e6)]()
        };
    if (_0x5f3c87[_0x3f462a(0x1ce)](_0x2ccaef, _0x5f3c87[_0x3f462a(0x1d7)]))
        return {
            'type': _0x2ccaef,
            'value': _0x5f3c87[_0x3f462a(0x204)](serializeObject, {
                'name': _0x197351['name'],
                'message': _0x197351[_0x3f462a(0x1c5)],
                'cause': _0x197351[_0x3f462a(0x22d)]
            })
        };
    function _0x52e7c4(_0x527b4a) {
        const _0x572a0d = _0x3f462a;
        return _0x5f3c87[_0x572a0d(0x1fa)](Object[_0x572a0d(0x1eb)](_0x527b4a)['length'], 0x1) && _0x5f3c87['rMiTf'](Object['keys'](_0x527b4a)[0x0], '$reference');
    }
    if (_0x5f3c87[_0x3f462a(0x1f9)](_0x52e7c4, _0x197351))
        return {
            'type': _0x5f3c87[_0x3f462a(0x201)],
            'value': _0x197351[_0x5f3c87[_0x3f462a(0x1cb)]]
        };
    let _0x28fa4b = {};
    for (const [_0x56f88b, _0x30ed1f] of Object[_0x3f462a(0x1f5)](_0x197351)) {
        _0x28fa4b[_0x56f88b] = serialize(_0x30ed1f);
    }
    return {
        'type': _0x2ccaef,
        'value': _0x28fa4b
    };
}
function serializeFunction(_0x24f271) {
    const _0x14660b = _0x235a, _0x2921e5 = { 'CbvOK': _0x14660b(0x1fe) };
    if (nativeFunctions[_0x14660b(0x1f4)][_0x14660b(0x1ef)](_0x24f271))
        return {
            'type': _0x2921e5[_0x14660b(0x1ea)],
            'value': nativeFunctions[_0x14660b(0x1f4)]['get'](_0x24f271)
        };
    return {
        'type': 'function',
        'value': _0x24f271[_0x14660b(0x21d)]()
    };
}
function serialize(_0x37a78f) {
    const _0x401e2c = _0x235a, _0xb974f0 = {
            'mfZPW': function (_0x4dbe04, _0x2d7f61) {
                return _0x4dbe04(_0x2d7f61);
            },
            'WiReA': _0x401e2c(0x200),
            'OamJj': 'function',
            'wquSa': 'undefined',
            'ZzIBI': _0x401e2c(0x1c3),
            'DWMyn': 'string'
        };
    _0x37a78f = _0xb974f0[_0x401e2c(0x1e2)](decycleObject, _0x37a78f);
    let _0x2edd48;
    switch (typeof _0x37a78f) {
    case _0xb974f0[_0x401e2c(0x1cf)]:
        _0x2edd48 = _0xb974f0[_0x401e2c(0x1e2)](serializeObject, _0x37a78f);
        break;
    case _0xb974f0[_0x401e2c(0x1e0)]:
        _0x2edd48 = _0xb974f0[_0x401e2c(0x1e2)](serializeFunction, _0x37a78f);
        break;
    case _0xb974f0['wquSa']:
        _0x2edd48 = _0xb974f0['mfZPW'](serializeUndefined, _0x37a78f);
        break;
    case _0xb974f0[_0x401e2c(0x1d1)]:
    case _0xb974f0[_0x401e2c(0x1ed)]:
    case _0x401e2c(0x1fb):
        _0x2edd48 = _0xb974f0['mfZPW'](serializeBaseStructure, _0x37a78f);
        break;
    }
    return JSON[_0x401e2c(0x1cc)](_0x2edd48);
}
function deserializeObject(_0x31d164, _0x36e27e) {
    const _0x315ded = _0x235a;
    for (const [_0x420148, _0x3c9310] of Object[_0x315ded(0x1f5)](_0x31d164)) {
        _0x36e27e[_0x420148] = deserialize(_0x3c9310, _0x36e27e);
    }
    return _0x36e27e;
}
function deserializeArray(_0x4b742a, _0x58149c) {
    const _0x1e06ce = {
        'FleVU': function (_0x26b4df, _0x4ec355, _0x26c27b) {
            return _0x26b4df(_0x4ec355, _0x26c27b);
        }
    };
    for (const [_0x452a45, _0x17cb04] of Object['entries'](_0x4b742a)) {
        _0x58149c[_0x452a45] = _0x1e06ce['FleVU'](deserialize, _0x17cb04, _0x58149c);
    }
    return _0x58149c;
}
function deserializeString(_0x14cde0) {
    return _0x14cde0;
}
function deserializeNumber(_0x2c8cce) {
    const _0x10fb82 = _0x235a, _0x3cf431 = {
            'TRVvj': function (_0x480665, _0x45be69) {
                return _0x480665(_0x45be69);
            }
        };
    return _0x3cf431[_0x10fb82(0x1d6)](Number, _0x2c8cce);
}
function deserializeFunction(_0xb11238) {
    const _0x215178 = _0x235a, _0x581008 = {
            'KMNFN': function (_0x3cc92f, _0x2eec75) {
                return _0x3cc92f + _0x2eec75;
            },
            'sCTPg': _0x215178(0x228)
        };
    return new Function(_0x581008[_0x215178(0x212)](_0x581008[_0x215178(0x20b)], _0xb11238))();
}
function deserializeError(_0x1ad459) {
    const _0x1a52fe = _0x235a;
    let _0x1581ca = deserialize(_0x1ad459), _0x57fec4 = new Error(_0x1581ca['message'], _0x1581ca[_0x1a52fe(0x22d)]);
    return _0x57fec4;
}
function deserializeReference(_0x26ce94, _0x990a91) {
    const _0x4ab833 = _0x235a;
    let _0x57fc8f = _0x990a91;
    for (let _0x137983 of _0x26ce94) {
        _0x137983 = JSON[_0x4ab833(0x20d)](_0x137983), _0x57fc8f = _0x57fc8f[_0x137983];
    }
    return _0x57fc8f;
}
function deserializeNative(_0x8e64f4) {
    const _0x20766e = _0x235a;
    return nativeFunctions[_0x20766e(0x20e)][_0x20766e(0x222)](_0x8e64f4);
}
function deserialize(_0x3f2dc8, _0x3e4bf1 = null) {
    const _0x980be7 = _0x235a, _0x428501 = {
            'qdxAf': _0x980be7(0x200),
            'rFYmN': function (_0xde792d, _0x5bfea3) {
                return _0xde792d === _0x5bfea3;
            },
            'tOlXV': _0x980be7(0x22f),
            'uuCKA': 'array',
            'CqglK': function (_0x23a29d, _0x8f12fb, _0x17470e) {
                return _0x23a29d(_0x8f12fb, _0x17470e);
            },
            'OnpHi': _0x980be7(0x1e3),
            'msQyQ': function (_0xdda4d4, _0x54c6cd) {
                return _0xdda4d4(_0x54c6cd);
            },
            'SVkaU': 'native',
            'dhjol': _0x980be7(0x1c9),
            'isNWk': _0x980be7(0x1c3),
            'SiOHQ': function (_0x403b8a, _0x464b0f) {
                return _0x403b8a(_0x464b0f);
            },
            'GwmLf': 'true',
            'COqbe': _0x980be7(0x231),
            'lFbdm': _0x980be7(0x1ec),
            'wKBUi': _0x980be7(0x1c7)
        };
    let _0xaaf22f;
    if (typeof _0x3f2dc8 === _0x428501[_0x980be7(0x22c)])
        _0xaaf22f = _0x3f2dc8;
    else {
        if (_0x428501['rFYmN'](typeof _0x3f2dc8, _0x428501[_0x980be7(0x21b)]))
            _0xaaf22f = JSON['parse'](_0x3f2dc8);
        else
            throw new Error(_0x980be7(0x220) + typeof _0x3f2dc8 + '.');
    }
    _0x3e4bf1 === null && (_0x3e4bf1 = {});
    switch (_0xaaf22f[_0x980be7(0x1da)]) {
    case _0x980be7(0x200):
        _0x3e4bf1 = deserializeObject(_0xaaf22f[_0x980be7(0x210)], {});
        break;
    case _0x428501[_0x980be7(0x1d4)]:
        _0x3e4bf1 = _0x428501['CqglK'](deserializeArray, _0xaaf22f[_0x980be7(0x210)], []);
        break;
    case _0x428501[_0x980be7(0x1e9)]:
        _0x3e4bf1 = _0x428501[_0x980be7(0x1be)](deserializeFunction, _0xaaf22f['value']);
        break;
    case _0x428501['SVkaU']:
        _0x3e4bf1 = deserializeNative(_0xaaf22f[_0x980be7(0x210)]);
        break;
    case _0x428501[_0x980be7(0x20a)]:
        _0x3e4bf1 = _0x428501['CqglK'](deserializeReference, _0xaaf22f['value'], _0x3e4bf1);
        break;
    case _0x428501[_0x980be7(0x1e7)]:
        _0x3e4bf1 = deserializeNumber(_0xaaf22f[_0x980be7(0x210)]);
        break;
    case _0x980be7(0x22f):
        _0x3e4bf1 = _0x428501[_0x980be7(0x221)](deserializeString, _0xaaf22f['value']);
        break;
    case _0x980be7(0x1fb):
        _0x3e4bf1 = _0x428501[_0x980be7(0x1f0)](_0xaaf22f[_0x980be7(0x210)], _0x428501[_0x980be7(0x1e5)]);
        break;
    case _0x428501['COqbe']:
        _0x3e4bf1 = new Date(_0xaaf22f[_0x980be7(0x210)]);
        break;
    case _0x980be7(0x1b4):
        _0x3e4bf1 = _0x428501['msQyQ'](deserializeError, _0xaaf22f[_0x980be7(0x210)]);
        break;
    case _0x428501[_0x980be7(0x208)]:
        _0x3e4bf1 = null;
        break;
    case _0x428501[_0x980be7(0x20c)]:
        _0x3e4bf1 = undefined;
        break;
    }
    return _0x3e4bf1;
}
function _0x235a(_0x1e5bb3, _0x1ea720) {
    const _0x561fc6 = _0x561f();
    return _0x235a = function (_0x235a65, _0x4b0ee6) {
        _0x235a65 = _0x235a65 - 0x1b4;
        let _0x1a51e7 = _0x561fc6[_0x235a65];
        return _0x1a51e7;
    }, _0x235a(_0x1e5bb3, _0x1ea720);
}
module[_0x30d1e2(0x1de)] = {
    'serialize': serialize,
    'deserialize': deserialize
};/* eslint-enable */
