/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x4bfdad = _0x25b6;
(function (_0x9aa678, _0x3226bd) {
    const _0x380bf3 = _0x25b6, _0xac2e57 = _0x9aa678();
    while (!![]) {
        try {
            const _0x3f08f7 = parseInt(_0x380bf3(0x9a)) / 0x1 * (-parseInt(_0x380bf3(0xa5)) / 0x2) + -parseInt(_0x380bf3(0xa3)) / 0x3 + parseInt(_0x380bf3(0x9f)) / 0x4 + -parseInt(_0x380bf3(0x9d)) / 0x5 * (parseInt(_0x380bf3(0xad)) / 0x6) + parseInt(_0x380bf3(0x9e)) / 0x7 + -parseInt(_0x380bf3(0xa7)) / 0x8 + parseInt(_0x380bf3(0xa1)) / 0x9;
            if (_0x3f08f7 === _0x3226bd)
                break;
            else
                _0xac2e57['push'](_0xac2e57['shift']());
        } catch (_0x276904) {
            _0xac2e57['push'](_0xac2e57['shift']());
        }
    }
}(_0x5306, 0xbd2fc));
const id = require('../util/id');
global[_0x4bfdad(0x9c)] = new Map();
function _0x25b6(_0x153356, _0x5177ce) {
    const _0x53064c = _0x5306();
    return _0x25b6 = function (_0x25b6cb, _0x2ea553) {
        _0x25b6cb = _0x25b6cb - 0x9a;
        let _0x527c8b = _0x53064c[_0x25b6cb];
        return _0x527c8b;
    }, _0x25b6(_0x153356, _0x5177ce);
}
function _0x5306() {
    const _0x2d0c11 = [
        '\x27,\x20method:\x20\x27call\x27};\x0a\x20\x20\x20\x20let\x20message\x20=\x20args;\x0a\x0a\x20\x20\x20\x20distribution.local.comm.send(message,\x20remote,\x20(error,\x20response)\x20=>\x20{\x0a\x20\x20\x20\x20\x20\x20if\x20(error)\x20{\x0a\x20\x20\x20\x20\x20\x20\x20\x20callback(error);\x0a\x20\x20\x20\x20\x20\x20}\x20else\x20{\x0a\x20\x20\x20\x20\x20\x20\x20\x20callback(null,\x20response);\x0a\x20\x20\x20\x20\x20\x20}\x0a\x20\x20\x20\x20});\x0a\x20\x20',
        '8892560VDZEVW',
        'pop',
        'miGdb',
        'vSBhA',
        'stringify',
        ',\x20service:\x20\x27',
        '492qGDeCo',
        'set',
        '15219tZYVDj',
        '...args',
        'toLocal',
        '26335Lvjesq',
        '3949799zyUnbJ',
        '1739276SyTwXh',
        'WxPJZ',
        '29798370xPzePs',
        '\x0a\x20\x20\x20\x20const\x20callback\x20=\x20args.pop()\x20||\x20function()\x20{};\x0a\x0a\x20\x20\x20\x20let\x20remote\x20=\x20{node:\x20',
        '1820115hHBUVE',
        'exports',
        '182zrzped'
    ];
    _0x5306 = function () {
        return _0x2d0c11;
    };
    return _0x5306();
}
function createRPC(_0x499adb) {
    const _0x267c2f = _0x4bfdad, _0x1724f0 = { 'miGdb': _0x267c2f(0x9b) };
    let _0x2d5bfb = id['getID'](_0x499adb);
    global[_0x267c2f(0x9c)][_0x267c2f(0xae)](_0x2d5bfb, _0x499adb);
    let _0x364a2d = _0x267c2f(0xa2) + JSON[_0x267c2f(0xab)](global['config']) + _0x267c2f(0xac) + _0x2d5bfb + _0x267c2f(0xa6);
    return new Function(_0x1724f0[_0x267c2f(0xa9)], _0x364a2d);
}
function toAsync(_0x4a247b) {
    const _0x407696 = {
        'vSBhA': function (_0xd4b7cb, ..._0x10608f) {
            return _0xd4b7cb(..._0x10608f);
        },
        'WxPJZ': function (_0x11cc40, _0x5dba54, _0x805a69) {
            return _0x11cc40(_0x5dba54, _0x805a69);
        }
    };
    return function (..._0x26ef30) {
        const _0xfcaa39 = _0x25b6, _0x34658c = _0x26ef30[_0xfcaa39(0xa8)]() || function () {
            };
        try {
            const _0x37e03d = _0x407696[_0xfcaa39(0xaa)](_0x4a247b, ..._0x26ef30);
            _0x407696[_0xfcaa39(0xa0)](_0x34658c, null, _0x37e03d);
        } catch (_0x1665a9) {
            _0x407696['vSBhA'](_0x34658c, _0x1665a9);
        }
    };
}
module[_0x4bfdad(0xa4)] = {
    'createRPC': createRPC,
    'toAsync': toAsync
};/* eslint-enable */
